### ISSUE TITLE
Unable to install pre-commit hook

### ISSUE THREAD

**Issue by chrisspen** [pre-commit/mirrors-yapf#11]
My `.pre-commit-config.yaml` looks like:

    repos:
    -   repo: https://github.com/pre-commit/mirrors-yapf
        rev: v0.30.0
        hooks:
        -   id: yapf
            args: [--in-place, --parallel, --recursive]

Yet when I try to commit, I get the error:

    [INFO] Initializing environment for https://github.com/pre-commit/mirrors-yapf.
    [INFO] Installing environment for https://github.com/pre-commit/mirrors-yapf.
    [INFO] Once installed this environment will be reused.
    [INFO] This may take a few minutes...
    An unexpected error has occurred: AssertionError: BUG: expected environment for python to be healthy() immediately after install, please open an issue describing your environment
    Check the log at /home/chris/.cache/pre-commit/pre-commit.log

The log shows:

    ### version information

    ```
    pre-commit version: 2.7.1
    sys.version:
        3.7.3 (default, Apr  3 2019, 19:16:38) 
        [GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]
    sys.executable: /home/chris/git/my-project/.env/bin/python3.7
    os.name: posix
    sys.platform: linux
    ```

    ### error information

    ```
    An unexpected error has occurred: AssertionError: BUG: expected environment for python to be healthy() immediately after install, please open an issue describing your environment
    ```

    ```
    Traceback (most recent call last):
      File "/home/chris/git/my-project/.env/lib/python3.7/site-packages/pre_commit/error_handler.py", line 63, in error_handler
        yield
      File "/home/chris/git/my-project/.env/lib/python3.7/site-packages/pre_commit/main.py", line 390, in main
        return run(args.config, store, args)
      File "/home/chris/git/my-project/.env/lib/python3.7/site-packages/pre_commit/commands/run.py", line 388, in run
        install_hook_envs(hooks, store)
      File "/home/chris/git/my-project/.env/lib/python3.7/site-packages/pre_commit/repository.py", line 206, in install_hook_envs
        _hook_install(hook)
      File "/home/chris/git/my-project/.env/lib/python3.7/site-packages/pre_commit/repository.py", line 87, in _hook_install
        f'BUG: expected environment for {hook.language} to be healthy() '
    AssertionError: BUG: expected environment for python to be healthy() immediately after install, please open an issue describing your environment

Is the yapf precommit hook not supported for Python3?

**Comment by asottile** [comment]
can you share a `pip freeze` and a `pip check` of your environment in `/home/chris/git/my-project/.env`?

**Comment by chrisspen** [comment]
Ah, thanks for the hint. Yes, I had a package version conflict between pre-commit and virtualenv.

**Comment by asottile** [comment]
cheers
