### ISSUE TITLE
pre-commit seems to not use python in venv

### ISSUE THREAD

**Issue by mikeyangyo** [pre-commit/mirrors-yapf#15]
Hi all,
I encounter an issue which seems that pre-commit does not use python in virtualenv.
Below info is my environment info.
- env: python 3.7 devcontainer in vscode
- modules:
    - yapf: v0.31.0
- config file:
    - `pyproject.toml` exist. But not use it to config yapf.
- description:
    when I use yapf hook (v0.31.0) in my project, I will got an issue for `toml` module is not installed. But this module was installed in my venv. So I think the major issue is that yapf hook use the python in container not in venv.
- Cause: [Code Origin](https://github.com/google/yapf/blob/v0.31.0/yapf/yapflib/style.py#L746)
```python
try:
    import toml
except ImportError:
    raise errors.YapfError(
        "toml package is needed for using pyproject.toml as a configuration file"
    )
```

And my current solution is **just change the language property from python to system**, and the issue is perfectly fixed

**Comment by asottile** [comment]
pre-commit intentionally installs separate environments to isolate the tools from your development environment (so your dev environment can be in any broken state)

it looks like yapf doesn't declare a dependency on `toml` so it doesn't get installed -- you can fix that though by specifying `additional_dependencies: [toml]`

**Comment by asottile** [comment]
for example:
```yaml
-   repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.31.0
    hooks:
    -   id: yapf
        additional_dependencies: [toml]
```

**Comment by stefsmeets** [comment]
Just ran into the same issue, took me a while to figure this one out. I don't have any yapf config specified, but it finds `pyproject.toml` causing this error:

`yapf: toml package is needed for using pyproject.toml as a configuration file`

With `pyproject.toml` becoming more prominent with the build system moving away from `setup.py`, would it make sense to add `toml` to the hook?

**Comment by mikeyangyo** [comment]
@asottile thanks for your reply.
Your answer works for me.
