### ISSUE TITLE
Yapf support toml but pre-commit does not

### ISSUE THREAD

**Issue by jefer94** [pre-commit/mirrors-yapf#22]
`pdm` use by default `pyproject.toml` and `yapf` get the toml file before `setup.cfg`

![image](https://user-images.githubusercontent.com/3018142/181693693-4bdfc53d-54ad-49d0-b7a7-8b1a6ef39888.png)

PR https://github.com/pre-commit/mirrors-yapf/pull/21

**Comment by asottile** [comment]
don't post screenshots of text: they're unsearchable, un copyable, and can't be read in my accessibility options

use `additional_dependencies`, it's exactly what this is designed for

**Comment by jefer94** [comment]
That resolve my issue 👍

```diff
-   repo: local
    hooks:
    -   id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        require_serial: true
    -   id: check-x
        name: Check X
        entry: ./bin/check-x.sh
        language: script
        files: \.x$
    -   id: scss-lint
        name: scss-lint
        entry: scss-lint
        language: ruby
        language_version: 2.1.5
        types: [scss]
+       additional_dependencies: ['scss_lint:0.52.0']
```
