### ISSUE TITLE
Specifying command line parameters?

### ISSUE THREAD

**Issue by chrisspen** [pre-commit/mirrors-yapf#8]
This hook only appears to run Yapf without any parameters. How do you specific options like `--in-place` or `--recursive`?

**Comment by asottile** [comment]
you're looking for [`args: [...]`](https://pre-commit.com/#pre-commit-configyaml---hooks) -- note that by default args is set to `-i` so if you override that you'll probably want to also include `-i`

**Comment by chrisspen** [comment]
Thanks.
